name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t nodekube-ci-cd:latest .
          docker tag nodekube-ci-cd:latest yasinsiddiquee/nodekube-ci-cd:latest
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u yasinsiddiquee --password-stdin
          docker push yasinsiddiquee/nodekube-ci-cd:latest

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

  notify:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Send Notification
        uses: appleboy/telegram-action@v0.4.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Deployment Status: ${{ job.status }}
            Repository: ${{ github.repository }}
